# Generated by Django 2.2.16 on 2022-04-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220401_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
