# Generated by Django 2.2.16 on 2022-04-03 16:58

from django.db import migrations, models
import django.db.models.expressions

def forwards_func(apps, schema_editor):
    Review = apps.get_model('reviews', 'Review')
    db_alias = schema_editor.connection.alias
    Review.objects.using(db_alias).filter(author=models.F('title')).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('title')), name='author_not_title_again'),
        ),
    ]
