# Generated by Django 2.2.16 on 2022-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220405_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, default='pole', max_length=256, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
