# Generated by Django 2.2.16 on 2022-04-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220402_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date', '-pk')},
        ),
    ]
